baseURL = 'https://eklem.github.io/portfolio/'
locale = 'en-us'
title = 'Espen Klem'
theme = 'beautifulhugo'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params]
  mainSections = ['posts']
  since = 2018
  [Params.author]
    github = 'eklem'
    linkedin = 'in/espen-klem'
    medium = 'eklem'
  custom_css = ["./css/override.css"]
  [[Params.bigimg]]
    src = "/portfolio/img/forside-illustrasjoner-02.png"
    desc = "Oversiktsbilde, diverse skisser, noen bilder og også skjermdumper."
    position = "center top"