baseURL = 'https://eklem.github.io/portfolio/'
locale = 'en-us'
title = 'Espen Klem'
theme = 'beautifulhugo'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params]
  mainSections = ['posts']
  since = 2018
  [Params.author]
    github = 'eklem'
    linkedin = 'espen-klem'
    medium = 'eklem'
  custom_css = ["./css/override.css"]
  [[Params.bigimg]]
    src = "img/espen-presentasjon-tegning.jpg"
    desc = "Presentasjon på internkonferanse om hvordan prosessen i å lære bort tegning for kommunikasjon."
    position = "center middle"